config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create, :destroy]
  end

  resources :ingredients, only: [:index, :show]

  root 'cocktails#index'

end

app/models/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when :alert   then "alert-error"
    when :notice  then "alert-success"
    end
  end
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :ingredient_id, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :find_cocktail, only: [:show, :destroy]
  def index
    @cocktails = Cocktail.all
  end
  def show
  end
  def new
    @cocktail = Cocktail.new
  end
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      flash[:notice] = "Cocktail #{@cocktail.name} has been created"
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end
  def destroy
    @cocktail = Cocktail.destroy(find_cocktail)
    flash[:notice] = "Cocktail #{@cocktail.name} has been deleted"
    redirect_to cocktails_path
  end
  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :picture)
  end
  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [ :new, :create, :destroy]

  def new
    @dose = Dose.new
  end

  def create
    @dose = @cocktail.doses.build(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end


  def destroy
    @dose = Dose.destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="text-center">
  <h1>My list of cocktails</h1>
  <%= link_to "Add cocktail", new_cocktail_path, class: "btn btn-primary" %>
</div>


<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <%= link_to cocktail.name, cocktail_path(cocktail) %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1 class="text-center">Add a new cocktail </h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name, placeholder: "Mojito" %>
        <%= f.input :picture %>
        <%= f.button :submit, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<h1 class="text-center"><%= @cocktail.name %></h1>
<p class="text-center"> <%= image_tag @cocktail.picture.url(:medium) %></p>

<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h3> Doses </h3>
        <% @cocktail.doses.each do |dose| %>
          <li>
            <%= dose.ingredient.name %> : <%= dose.description %>
          </li>
        <% end %>
      <%= link_to "Delete cocktail", cocktail_path(@cocktail), method: :delete, data: { confirm: 'Are you sure you want to delete this cocktail?' }, class: "btn btn-danger" %>
      <%= link_to "Back to cocktails list", cocktails_path, class: "btn btn-primary" %>
      <%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<h1 class="text-center">Add a new dose for <%= @cocktail.name %></h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.association :ingredient, prompt: "Select an ingredient" %>
        <%= f.input :description, label: "Quantité ?", placeholder: "3cl" %>
        <%= f.button :submit, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/index.html.erb
<div class="text-center">
  <h1>My list of ingredients</h1>
</div>

<div class="container text-center">
  <div class="row">
    <% @ingredients.each do |ingredient| %>
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <%= link_to ingredient.name, ingredient_path(ingredient) %>
      </div>
    <% end %>
  </div>
</div>

app/views/ingredients/show.html.erb
<h1 class="text-center">Cocktails containing <%= @ingredient.name %></h1>

<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <% @ingredient.cocktails.each do |cocktail| %>
        <li>
          <%= cocktail.name %>
        </li>
      <% end %>
      <p><%= link_to "Back to ingredients list", ingredients_path %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktail</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/navbar" %>

<%= render 'shared/flash' %>

<%= yield %>

</body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-error fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <%= link_to image_tag("logo.png"), cocktails_path %>

    <div class="navbar-wagon-pusher"></div>

    <hr class="hidden-xs hidden-sm">
      <%= link_to ingredients_path, class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-lemon-o"></i>
          <div class="icon-badge icon-badge-blue"><%= Ingredient.count %></div>
        </div>
      <% end %>
      <hr>

      <hr class="hidden-xs hidden-sm">
      <%= link_to cocktails_path, class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-glass"></i>
          <div class="icon-badge icon-badge-blue"><%= Cocktail.count %></div>
        </div>
      <% end %>
      <hr>
    <%= link_to t(".top_call_to_action", default: "New Cocktail"), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>